#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr  5 14:44:29 2023

@author: student
"""

import numpy as np 
import pickle
import streamlit as st
#Loading the Saved Model
loaded_model=pickle.load(open('/home/student/Desktop/diabeties prediction/trained_model.sav','rb'))
# Creating a function for prediction
def diabetes_prediction(input_data):
    
    input_data =(4,110,92,0,0,37.6,0.191,30)

    # changing the input_data to numpy array
    input_data_as_numpy_array = np.asarray(input_data)

    # reshape the array as we are predicting for one instance
    input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)


    prediction = loaded_model.predict(input_data_reshaped)
    print(prediction)

    if (prediction[0] == 0):
      return 'The person is not diabetic'
    else:
      return'The person is diabetic'
      
      
      
      
      
def main():
    #Giving a title 
    st.title('DIABETES PREDICTION WEB APP')
    
    # Getting the input data from User
    
    
